services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '${APP_PORT:-8000}:8000'
        environment:
            APP_URL: 'http://127.0.0.1:${APP_PORT:-8000}'
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: '${DB_DATABASE:-escola_fps}'
            DB_USERNAME: root
            DB_PASSWORD: '${DB_PASSWORD:-}'
        volumes:
            - '.:/var/www/html'
        depends_on:
            mysql:
                condition: service_healthy

    mysql:
        image: 'mysql:8.4'
        ports:
            - '${FORWARD_DB_PORT:-3308}:3306'
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_DATABASE: '${DB_DATABASE:-escola_fps}'
            MYSQL_ROOT_HOST: '%'
        volumes:
            - 'mysql-data:/var/lib/mysql'
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', '127.0.0.1']
            interval: 5s
            retries: 10
            timeout: 5s

volumes:
    mysql-data:
        driver: local
